export const DATA_DIR = "data/"
export const PINS_DIR = DATA_DIR + "pins/"
export const UPLOADS_DIR = DATA_DIR + "uploads"
export const PUBLIC_UPLOADS_PATH = "/uploads/"
export const HOST_DOMAIN = "localhost:3000"
